### ISSUE TITLE
Investigate CI failure 

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-waiters#149]
```
ReferenceError: _EmberTestRegisterWaiter is not defined
42
                at Module.callback (http://localhost:7357/assets/vendor.js:62823:5)
43
                at Module.exports (http://localhost:7357/assets/vendor.js:118:32)
44
                at Module._reify (http://localhost:7357/assets/vendor.js:155:59)
45
                at Module.reify (http://localhost:7357/assets
```

From https://github.com/emberjs/ember-test-waiters/commit/107787f455c4212ae281566bcf36fc94edbda81e/checks?check_suite_id=722141915

**Comment by stefanpenner** [comment]
CI is happy
