### ISSUE TITLE
maybe an embroider compatibility issue? can't find module

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember-test-waiters#158]
Over on this branch: https://github.com/NullVoxPopuli/emberclear/pull/922
CI Log: (shows a different error related to broccoli-persistent-filter, so nothing useful there)

But locally, I got this this error:
```
Build Error (PackagerRunner)

Module not found: Error: Can't resolve 'ember-test-waiters/@ember/test-waiters/index.ts' in '/tmp/embroider/1fa051/emberclear/components/pod/chat/chat-entry'


Stack Trace and Error Report: /tmp/error.dump.7513682a37c80366568ac0ad779c60e4.log
```

At first, I was confused about why ember-test-waiters would be imported from an app file, but then [looking at the file](https://github.com/NullVoxPopuli/emberclear/blob/master/client/web/emberclear/app/components/pod/chat/chat-entry/index.ts), I see that I'm doing 
```ts
import { waitForPromise } from '@ember/test-waiters';
```
which makes sense. (also reminded myself what ember-test-waiters was even for, cause it's been a while since I've done a lot with this project)

<details>
<summary>within the error dump</summary>

```
=================================================================================

ENV Summary:

  TIME: Sat Jun 06 2020 22:59:10 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/bin/node
  - /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/.bin/ember
  - serve
  - -p
  - 4201
  EXEC_PATH: /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1591498689832-0.1412731329260819
  - /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/emberclear/node_modules/.bin
  - /home/lprestonsegoiii/.config/yarn/link/node_modules/.bin
  - /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/.bin
  - /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/lib/node_modules/npm/bin/node-gyp-bin
  - /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/bin/node_modules/npm/bin/node-gyp-bin
  - /tmp/yarn--1591498689486-0.8795073939338094
  - /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/emberclear/node_modules/.bin
  - /home/lprestonsegoiii/.config/yarn/link/node_modules/.bin
  - /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/.bin
  - /home/lprestonsegoiii/.yarn/bin
  - /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/lib/node_modules/npm/bin/node-gyp-bin
  - /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/bin/node_modules/npm/bin/node-gyp-bin
  - /home/lprestonsegoiii/.volta/tools/image/yarn/1.22.4/bin
  - /home/lprestonsegoiii/.volta/tools/image/node/14.4.0/bin
  - /home/lprestonsegoiii/.pythons/Python-3.6.3/bin
  - /home/lprestonsegoiii/.cargo/bin
  - /home/lprestonsegoiii/Applications
  - /home/lprestonsegoiii/apps/phantomjs/bin
  - /home/lprestonsegoiii/scripts/system-utils
  - /home/lprestonsegoiii/scripts/git
  - /home/lprestonsegoiii/scripts/rails
  - /home/lprestonsegoiii/scripts
  - /home/lprestonsegoiii/.cargo/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/lprestonsegoiii/.fzf/bin
  - /home/lprestonsegoiii/.rvm/bin
  PLATFORM: linux x64
  FREEMEM: 333049856
  TOTALMEM: 8226172928
  UPTIME: 635092
  LOADAVG: 2.6318359375,2.02685546875,1.54248046875
  CPUS:
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2271
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2415
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2446
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2599
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.0
  - brotli: 1.0.7
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.0.4
  - modules: 83
  - napi: 6
  - nghttp2: 1.41.0
  - node: 14.4.0
  - openssl: 1.1.1g
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.37.0
  - v8: 8.1.307.31-node.33
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve 'ember-test-waiters/@ember/test-waiters/index.ts' in '/tmp/embroider/1fa051/emberclear/components/pod/chat/chat-entry'
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/Compilation.js:925:10
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/neo-async/async.js:2830:7
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/neo-async/async.js:6877:13
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:27:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:28:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:16:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:16:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:27:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:16:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve 'ember-test-waiters/@ember/test-waiters/index.ts' in '/tmp/embroider/1fa051/emberclear/components/pod/chat/chat-entry'
  - errorMessage: Module not found: Error: Can't resolve 'ember-test-waiters/@ember/test-waiters/index.ts' in '/tmp/embroider/1fa051/emberclear/components/pod/chat/chat-entry'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:45:31)
    at new PackagerRunner (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at defaultPipeline (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/@embroider/compat/src/default-pipeline.js:36:12)
    at module.exports (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/emberclear/ember-cli-build.js:118:12)
    at Builder.readBuildFile (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:29:10)
    at ServeTask.run (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/models/command.js:238:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Module not found: Error: Can't resolve 'ember-test-waiters/@ember/test-waiters/index.ts' in '/tmp/embroider/1fa051/emberclear/components/pod/chat/chat-entry'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:45:31)
    at new PackagerRunner (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at defaultPipeline (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/@embroider/compat/src/default-pipeline.js:36:12)
    at module.exports (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/emberclear/ember-cli-build.js:118:12)
    at Builder.readBuildFile (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/models/builder.js:29:10)
    at ServeTask.run (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/ember-cli/lib/models/command.js:238:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

-~- (end) -~-
  - name: Error
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve 'ember-test-waiters/@ember/test-waiters/index.ts' in '/tmp/embroider/1fa051/emberclear/components/pod/chat/chat-entry'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve 'ember-test-waiters/@ember/test-waiters/index.ts' in '/tmp/embroider/1fa051/emberclear/components/pod/chat/chat-entry'
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/Compilation.js:925:10
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/neo-async/async.js:2830:7
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/neo-async/async.js:6877:13
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:27:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:28:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:16:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:16:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:27:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:16:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (<anonymous>:15:1)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/client/web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)


=================================================================================

```

</details>

This is with the alpha version of ember-cli-typescript and embroider 0.19.0

Also maybe cc @chriskrycho & @ef4 ?

**Comment by rwjblue** [comment]
Can you confirm which version you are using?

**Comment by NullVoxPopuli** [comment]
sure can!
```
$ yarn why ember-test-waiters
yarn why v1.22.4
[1/4] Why do we have the module "ember-test-waiters"...?
[2/4] Initialising dependency graph...
warning Resolution field "ember-test-waiters@2.1.2" is incompatible with requested version "ember-test-waiters@^1.1.1"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "ember-test-waiters@2.1.2"
info Reasons this module exists
   - "_project_#emberclear" depends on it
   - Hoisted from "_project_#emberclear#ember-test-waiters"
   - Hoisted from "_project_#emberclear#@ember#test-helpers#ember-test-waiters"
   - Hoisted from "_project_#emberclear#ember-router-scroll#ember-app-scheduler#ember-test-waiters"
info Disk size without dependencies: "776KB"
info Disk size with unique dependencies: "3.09MB"
info Disk size with transitive dependencies: "45.05MB"
info Number of shared dependencies: 157
```

was curious about the resolutions thing:
```
$ git grep "resolutions"
package.json:  "resolutions": {

$ cat package.json | jq '.resolutions'
{
  "ember-test-waiters": "2.1.2"
}
```
pretty sure I added that because of some runtime issue with ember-test-waiters not being found (the issue that was fixed in the 2.1.2 release?) Not sure why it keeps coming up. 
```
$ yarn --version
1.22.4
$ node --version
v14.4.0
```

**Comment by rwjblue** [comment]
My guess is that the issue here is that we are making both `@ember/test-waiters` and `ember-test-waiters` available (as a transition path), and that Embroider is confused (we really aren't following "normal" addon paradigms). 

The Ember addon v2 RFC adds support for this kind of aliasing / renaming, but I don't know if I can use some of those features now (before we can actually use V2 "for real"). 

@ef4 - Do you happen to know?

**Comment by ef4** [comment]
The aliasing by itself shouldn’t be a problem.

Does this pattern actually work without embroider? I’m not sure test waiters is designed to be consumed directly by the app.

**Comment by NullVoxPopuli** [comment]
> I’m not sure test waiters is designed to be consumed directly by the app.

how else is `waitForPromise` supposed to be used?

**Comment by ef4** [comment]
(It’s only the compatibility code that would cause such a distinction. If test waiters wasn’t doing shenanigans you could of course import any part of it into any part of your code and it would work.

**Comment by rwjblue** [comment]
> Does this pattern actually work without embroider?

Ya, it works in "classic" build.

> I’m not sure test waiters is designed to be consumed directly by the app.

Yes, the idea of the API is that this code is "left in app code" (this is one of those cases where "are we running tests or not" is important, so that we can ensure this code is properly stripped out, but that is somewhat orthogonal).

**Comment by rwjblue** [comment]
@NullVoxPopuli - Can you make a branch or something that exhibits the error and push it up (and tell me what commands are needed to run to get the failure you mentioned above)? I'll try to poke at it this week.

**Comment by NullVoxPopuli** [comment]
yeah, however, this may be a compound issue, as I'm also testing out the alpha version of ec-typescript

this will get you a reproducible error:
```
git clone git@github.com:NullVoxPopuli/emberclear.git
git checkout embroider-with-alpha-ec-cs
cd client/web/emberclear/
yarn
yarn start # or yarn ember test
```

**Comment by ef4** [comment]
I think I found an embroider bug that broke ember-test-waiters. It happens when an add-on is both trying to fake its package name *and* it's authored in typescript. https://github.com/embroider-build/embroider/pull/475

**Comment by rwjblue** [comment]
Nice! Thanks for digging in here @ef4!

**Comment by scalvert** [comment]
Just saw this! Thanks for looking into this and fixing, @ef4. Hopefully the weird package name faking will be resolved soon.

**Comment by NullVoxPopuli** [comment]
I checked out that branch with the fix, and I can confirm that it resolves the issue :D

**Comment by scalvert** [comment]
Can this be closed?
